// src/App.vue
<template>
  <div id="app" class="ui container">
    <!-- HEADER -->
    <div id="header">
      <h2 class="ui header centered">
        <img alt="logo" src="./assets/logo.png" />
        <div class="content">
          GOG Russian Prices
          <div class="sub header">Where you can save on GOG.com</div>
          <div v-if="lastUpdated" class="sub header">Last update: {{lastUpdated}}</div>
          <div v-if="showAlt" class="sub header">
            We are moving to
            <a href="https://gogputin.web.app">gogputin.web.app</a>
          </div>
        </div>
      </h2>
    </div>
    <!-- END HEADER -->

    <div class="ui divider"></div>

    <!-- SEARCH BAR -->
    <div class="ui centered grid">
      <div id="search" class="ui search middle aligned content">
        <div class="ui icon input">
          <input
            aria-label="search"
            class="prompt"
            type="text"
            v-model="searchText"
            @keyup="search"
            placeholder="Search game..."
          />
          <i class="search icon"></i>
        </div>
      </div>
    </div>
    <!-- END SEARCH BAR -->

    <div class="ui divider"></div>

    <!-- GAME LIST -->
    <div id="game-list">
      <div v-if="searching" class="ui active centered inline loader"></div>

      <h1
        v-if="!searching && showing.length == 0"
        class="ui header centered"
      >No results looking for: {{searchText}}</h1>

      <div
        v-infinite-scroll="loadMore"
        infinite-scroll-disabled="busy"
        infinite-scroll-distance="100"
        class="ui five doubling cards link"
      >
        <template v-for="game in showing">
          <game :info="game" :key="game.id"></game>
        </template>
      </div>
    </div>
    <!-- END GAME LIST -->
  </div>
</template>

<script>
import debounce from "lodash/debounce";
import Game from "./components/Game";
const PAGE = 20;

export default {
  data() {
    return {
      games: [],
      curPage: 1,
      searchText: "",
      showing: [],
      searching: true,
      showAlt: false,
      lastUpdated: undefined,
      all: false
    };
  },
  name: "app",
  components: {
    game: Game
  },
  created() {
    fetch("https://raw.githubusercontent.com/Dionakra/gog-russian-prices/master/public/sales.json")
      .then(response => response.json())
      .then(data => {
        this.games = Object.values(data)
        this.showing = this.filterGames(Object.values(data));
      });

    fetch("https://raw.githubusercontent.com/Dionakra/gog-russian-prices/master/public/lastUpdate.json")
      .then(response => response.json())
      .then(data => {
        const lastUpdated = data.last;
        const day = lastUpdated.substr(8, 2);
        const month = lastUpdated.substr(5, 2);
        const hour = lastUpdated.substr(11, 5);
        this.lastUpdated = `${day}/${month} - ${hour}`;
      });
  },
  mounted() {
    this.showAlt = window.location.href.includes("gog.dionakra");
  },
  methods: {
    loadMore() {
      if (!this.searching) {
        this.curPage++;
        this.showing = this.filterGames();
      }
    },
    filterGames(collection = undefined) {
      const term = this.searchText;
      this.searching = true;
      let res = [];

      const col = collection || this.games;
      if (col) {
        res = col
          .filter(game => {
            let res = false;

            if (term) {
              res = game.title.toLowerCase().includes(term.toLowerCase());
            } else {
              res = game.sale != undefined;
            }

            return res;
          })
          .sort((a, b) => a.title.toLowerCase().localeCompare(b.title.toLowerCase()))
          .slice(0, PAGE * this.curPage);
      }
      this.searching = false;
      return res;
    },
    search: debounce(async function() {
      if (!this.all) {
        const data = await fetch(
          "https://raw.githubusercontent.com/Dionakra/gog-russian-prices/master/public/games.json"
        ).then(response => response.json());
        this.games = Object.values(data);
        this.all = true;
      }

      this.curPage = 1;
      this.showing = this.filterGames();
    }, 500)
  }
};
</script>

<style>
.custom-blue {
  background-color: #2574a9 !important;
  color: #fff !important;
}
.custom-green {
  background-color: #1e824c !important;
  color: #fff !important;
}

.custom-red {
  background-color: #96281b !important;
  color: #fff !important;
}
div#game-list {
  padding-top: 10px;
}
div#header {
  padding-top: 10px;
}
div#search {
  padding-top: 8px;
  padding-bottom: 8px;
}
</style>

// src/App.svelte
<script>
  const BASE_URL =
    "https://raw.githubusercontent.com/Dionakra/gog-russian-prices/master/public";
  const PAGE_SIZE = 24;

  import { onMount } from "svelte";

  export let searchResult = [];
  export let searchTerm = "";

  export let games = [];
  export let sales = [];
  export let lastUpdated = "";
  export let showAlt = false;
  export let totalPages = -1;
  export let currentPage = -1;
  $: pageContent = searchResult.slice(
    (currentPage - 1) * PAGE_SIZE,
    currentPage * PAGE_SIZE
  );

  onMount(async () => {
    showAlt = window.location.href.includes("dionakra");

    await fetch(`${BASE_URL}/sales.json`)
      .then((response) => response.json())
      .then((data) => {
        sales = data.sort((a, b) => a.title.localeCompare(b.title));
        searchResult = sales;
        totalPages = Math.floor(sales.length / PAGE_SIZE) + 1;
        currentPage = 1;
      });

    await fetch(`${BASE_URL}/lastUpdate.json`)
      .then((response) => response.json())
      .then((data) => {
        const last = data.last;
        const day = last.substr(8, 2);
        const month = last.substr(5, 2);
        const hour = last.substr(11, 5);
        lastUpdated = `${day}/${month} - ${hour}`;
      });
  });

  async function search() {
    if (searchTerm.trim() == "") {
      searchResult = sales;
    } else {
      if (games.length === 0) {
        await fetch(`${BASE_URL}/games.json`)
          .then((r) => r.json())
          .then((data) => {
            games = data.sort((a, b) => a.title.localeCompare(b.title));
          });
      }

      searchResult = games.filter((game) =>
        game.title.toLowerCase().includes(searchTerm.trim().toLowerCase())
      );
      totalPages = Math.floor(searchResult.length / PAGE_SIZE) + 1;
      currentPage = 1;
    }
  }

  const onKeyPress = (e) => {
    if (e.charCode === 13) search();
  };

  const moveOnKeyPress = (e) => {
    if(e.target.id === "searchterm") return
    if (e.keyCode === 37) previousPage();
    if (e.keyCode === 39) nextPage();
  };

  const openLink = (url) => {
    let win = window.open(`https://www.gog.com${url}`, "_blank");
    win.focus();
  };

  function nextPage() {
    if (currentPage < totalPages) movePage(1);
  }
  function previousPage() {
    if (currentPage > 1) movePage(-1);
  }

  function movePage(direction) {
    currentPage = currentPage + direction;
    document.getElementById("games").scrollIntoView();
  }
</script>

<svelte:window on:keydown={moveOnKeyPress}/>

<main class="container mx-auto px-3" >
  <div class="flex flex-wrap justify-center items-center">
    <div class="w-full flex justify-center">
      <!-- HEADER -->
      <div class="block space-y-3 w-full md:w-1/3 py-3">
        <!-- TITLE -->
        <div class="justify-center w-full">
          <h1 class="text-center text-3xl font-extrabold text-gray-900 ">
            GOG Russian Prices
          </h1>
          {#if showAlt}
            <p class="text-sm text-gray-700 text-center">
              We are moving to
              <a
                class="text-blue-700 underline"
                href="https://gogputin.web.app">gogputin.web.app</a>
            </p>
          {/if}

          {#if lastUpdated}
            <p class="text-sm text-gray-700 text-center pt-1">
              Last update:
              {lastUpdated}
            </p>
          {/if}
        </div>
        <!-- END TITLE -->

        <!-- SEARCH -->
        <div class="rounded-md shadow-sm -space-y-px">
          <div>
            <label for="searchterm" class="sr-only">Search Term</label>
            <input
              bind:value={searchTerm}
              on:keypress={onKeyPress}
              id="searchterm"
              name="searchterm"
              type="text"
              required
              class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
              placeholder="Search for your game!" />
          </div>
        </div>

        <div>
          <button
            on:click={search}
            type="submit"
            class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            <span class="absolute left-0 inset-y-0 flex items-center pl-3" />
            Search!
          </button>
        </div>
        <!-- END SEARCH -->
      </div>
      <!-- END HEADER -->
    </div>

    <!-- RESULTS -->
    <div class="flex block w-full" id="games">
      <div class="flex flex-wrap w-full" role="list">
        {#each pageContent as game}
          <div
            on:click={openLink(game.url)}
            class="cursor-pointer flex flex-col w-1/2 md:w-1/3 lg:w-1/4 xl:w-1/5 2xl:w-1/6 px-1 pb-3"
            role="listitem">
            <div
              class="rounded overflow-hidden hover:shadow-lg border-r border-b border-l border-gray-300 flex-1">
              <img
                class="w-full"
                src={game.image + '_200.jpg'}
                alt={game.title}
                title={game.title}
                loading="lazy" />
              <div class="px-2 py-2">
                <div class="font-bold text-md">{game.title}</div>
                <div class="text-sm text-gray-600">{game.category}</div>
              </div>
              <!-- PRICES -->
              <div class="pl-3 space-y-3 pb-3">
                <div class="flex flex-inline h-5">
                  <img class="h-full" src="/ru.svg" alt="Russian Flag" />
                  {#if game.sale}
                    <span
                      class="font-medium text-blue-700 pl-2">{game.sale.ru}$</span>
                    <span
                      class="text-sm text-red-700 line-through pl-2">{game.price.ru}$</span>
                  {:else}
                    <span class="font-medium pl-2">{game.price.ru}$</span>
                  {/if}
                </div>

                <div class="flex flex-inline h-5">
                  <img class="h-full" src="/es.svg" alt="Spanish Flag" />
                  {#if game.sale}
                    <span
                      class="font-medium text-blue-700 pl-2">{game.sale.es}$</span>
                    <span
                      class="text-red-700 line-through pl-2">{game.price.es}$</span>
                  {:else}
                    <span class="font-medium pl-2">{game.price.es}$</span>
                  {/if}
                </div>
              </div>
              <!-- END PRICES -->
            </div>
          </div>
        {/each}
      </div>
    </div>
    <!-- END RESULTS-->

    <!-- PAGINATION -->
    <div class="flex flex-inline block w-full mb-2">
      <div class="w-1/3 px-1 ">
        <button
          on:click={previousPage}
          disabled={currentPage <= 1}
          class="disabled:opacity-50 group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          &lt;&lt; Previous</button>
      </div>

      <div class="w-1/3 px-1 ">
        <div
          class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          {currentPage}
          /
          {totalPages}
        </div>
      </div>

      <div class="w-1/3 px-1 ">
        <button
          on:click={nextPage}
          disabled={currentPage >= totalPages}
          class="disabled:opacity-50 group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          Next &gt;&gt;</button>
      </div>
    </div>

    <!-- END PAGINATION -->
  </div>
</main>
